CREATE OR REPLACE VIEW public.view_employees
AS
SELECT e.id,
       e.user_id,
       e.nationality_id,
       e.born_date,
       e.gender,
       e.first_work_date,
       e.leave_date,
       e.contract_number,
       e.contract_date,
       e.phone,
       e.telegram,
       e.avatar,
       e.email,
       e.note,
       e.responsible_id,
       e.is_active,
       e.is_accessible,
       e.inn,
       e.inps,
       e.created_by,
       e.updated_by,
       e.deleted_by,
       e.created_at,
       e.updated_at,
       e.deleted_at,
       et.id AS employee_translation_id,
       et.language_code,
       et.first_name,
       et.last_name,
       et.middle_name
FROM employees e
         LEFT JOIN employee_translations et ON e.id = et.object_id;
